version: '3'

services:
  client:
    container_name: courier-app-client
    restart: always
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - './client:/app/client'
    links:
      - server

  server:
    container_name: courier-app-server
    restart: always
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - './server:/app/server'
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
